name: frontend
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  go_router: ^16.0.0
  flutter_dotenv: ^5.2.1
  http: ^1.4.0
  image_picker: ^1.1.2
  shared_preferences: ^2.5.3
  provider: ^6.1.5
  path: ^1.9.1
  sqflite: ^2.4.2
  crypto: ^3.0.0

  firebase_core: ^4.0.0
  firebase_messaging: ^16.0.0
  cloud_firestore: ^6.0.0
  flutter_local_notifications: ^17.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - .env
