// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQNKSWL-DkFB5WcNaM9UNfq387tyzRW1A',
    appId: '1:150105218912:web:42e6cf87232815147f8805',
    messagingSenderId: '150105218912',
    projectId: 'medihome-8029e',
    authDomain: 'medihome-8029e.firebaseapp.com',
    storageBucket: 'medihome-8029e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAX1jee_WailFyqG360jNMT9jwp-4DagOE',
    appId: '1:150105218912:android:a903b84950634fea7f8805',
    messagingSenderId: '150105218912',
    projectId: 'medihome-8029e',
    storageBucket: 'medihome-8029e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1ZywoW9rpSPSYrf3a0ByCEQdfAP94YQg',
    appId: '1:150105218912:ios:0c6394b7038049d17f8805',
    messagingSenderId: '150105218912',
    projectId: 'medihome-8029e',
    storageBucket: 'medihome-8029e.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1ZywoW9rpSPSYrf3a0ByCEQdfAP94YQg',
    appId: '1:150105218912:ios:0c6394b7038049d17f8805',
    messagingSenderId: '150105218912',
    projectId: 'medihome-8029e',
    storageBucket: 'medihome-8029e.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQNKSWL-DkFB5WcNaM9UNfq387tyzRW1A',
    appId: '1:150105218912:web:16fe473b1dbaa1587f8805',
    messagingSenderId: '150105218912',
    projectId: 'medihome-8029e',
    authDomain: 'medihome-8029e.firebaseapp.com',
    storageBucket: 'medihome-8029e.firebasestorage.app',
  );
}
